-- Draft AnyKit Lab product catalog entries derived from verified Canva designs.
-- Products are inserted as Draft except the existing live fitness mini-pack metadata correction.
-- Buyer-facing Canva Template Links still need to be added/confirmed before publishing new products.

update public.akl_products
set
  layout_count = 8,
  description = 'An 8-page editable Canva mini pack for fitness coaches, gyms and wellness brands that need quick social posts for programs, schedules, testimonials, pricing and calls to action.',
  long_description = 'This mini fitness pack contains eight square Canva layouts for common gym and coaching content: program announcements, weekly schedules, coach introductions, client wins, membership plans, training tips and conversion-focused calls to action. Replace the text, prices, photos and booking details with your own brand content before posting.',
  formats = array['Square posts', 'Instagram posts', 'Offer slides', 'Fitness content'],
  includes = array[
    '8 editable square Canva layouts',
    'Program launch post',
    'Weekly schedule post',
    'Coach introduction post',
    'Client win/testimonial post',
    'Membership pricing post',
    'Fitness tip post',
    'Call-to-action post'
  ],
  badge = '8 Pages'
where slug = 'fitness-brand-social-media-template-pack';

insert into public.akl_products (
  id,
  slug,
  title,
  category_id,
  collection_id,
  price,
  mrp,
  layout_count,
  description,
  long_description,
  cover_url,
  accent,
  dark,
  badge,
  status,
  formats,
  includes,
  cover_name,
  delivery_name
)
values
  (
    'tpl-canva-gym-fitness-30-posts',
    'gym-fitness-instagram-templates-30-posts',
    'Gym & Fitness Instagram Templates — 30 Posts',
    'cat-fitness',
    'col-social',
    799,
    1499,
    32,
    'A 30-post editable Canva template pack for gyms, coaches, trainers and fitness studios that need a ready-to-customize Instagram content system.',
    'This pack gives fitness businesses a practical content library for launching programs, promoting coaching offers, sharing client wins, posting training tips, showing schedules and driving bookings. Replace the photos, logo, colors, prices and booking links in Canva, then export and post.',
    '/assets/canva-products/gym-fitness-instagram-templates-30-posts.png',
    '#b8ff64',
    '#191917',
    '30 Posts',
    'Draft',
    array['Square posts', 'Instagram templates', 'Coaching posts', 'Offer slides'],
    array[
      '30 editable gym and fitness Instagram post templates',
      '1 cover page',
      '1 how-to-edit guide page',
      'Coach intro, program launch and coaching offer layouts',
      'Timetable, weekly workout, tips, testimonials, progress, offers, FAQ and CTA layouts'
    ],
    'gym-fitness-instagram-templates-30-posts.png',
    ''
  ),
  (
    'tpl-canva-detail-marketing-system',
    'detail-authority-marketing-content-system',
    'The Detail Authority — High-End Marketing Content System',
    'cat-auto',
    'col-social',
    1499,
    2999,
    48,
    'A premium 48-page Canva marketing system for auto detailers who want polished service content, booking posts, story templates, reel covers and highlight covers.',
    'Built for detailing studios and premium car-care businesses, this system helps present transformations, ceramic protection, service packages, reviews, booking availability, referrals and highlight content with a consistent high-end visual identity. Replace vehicle photos, prices, service areas and booking links to launch a professional content system quickly.',
    '/assets/canva-products/detail-authority-marketing-content-system.png',
    '#d28a38',
    '#151412',
    '48 Pages',
    'Draft',
    array['Feed posts', 'Stories', 'Reel covers', 'Highlight covers'],
    array[
      '18 automotive detailing feed/content pages',
      '10 Instagram story templates',
      '8 reel cover templates',
      '12 highlight cover templates',
      'Premium placeholders for vehicle photos, booking links, service areas, offers and calls to action'
    ],
    'detail-authority-marketing-content-system.png',
    ''
  ),
  (
    'tpl-canva-detail-sales-pricing',
    'detail-authority-sales-pricing-system',
    'The Detail Authority — Sales & Pricing System',
    'cat-auto',
    'col-launch',
    999,
    1999,
    17,
    'A sales and pricing Canva system for auto detailers to present packages, add-ons, offers, flyers and booking materials professionally.',
    'Use this kit to turn detailing services into clear, premium pricing and sales assets. It includes menus, package comparisons, quote-style sheets, customer offers and print-friendly marketing pieces that can be customized with your brand, prices, vehicle photos and booking links.',
    '/assets/canva-products/detail-authority-sales-pricing-system.png',
    '#d28a38',
    '#151412',
    'Sales Kit',
    'Draft',
    array['Price guides', 'Service menus', 'Flyers', 'Business cards'],
    array[
      'Luxury service menu cover',
      'Interior and exterior detailing price guides',
      'Full detail and ceramic package guides',
      'Add-ons menu and three-package comparison sheet',
      'Vehicle size pricing matrix, offer cards, brochure, QR flyer, door hanger and business cards'
    ],
    'detail-authority-sales-pricing-system.png',
    ''
  ),
  (
    'tpl-canva-detail-client-ops',
    'detail-authority-client-experience-operations-kit',
    'The Detail Authority — Client Experience & Operations Kit',
    'cat-auto',
    'col-launch',
    999,
    1999,
    16,
    'A client-experience operations kit for auto detailers to handle enquiries, bookings, preparation, aftercare, reviews and rebooking with polished Canva templates.',
    'This kit helps detailing businesses look more professional before, during and after each appointment. Customize the forms, checklists, cards and aftercare templates to match your process. Template only; adapt all operational and legal wording for your local business requirements.',
    '/assets/canva-products/detail-authority-client-experience-operations-kit.png',
    '#d28a38',
    '#151412',
    'Ops Kit',
    'Draft',
    array['Client forms', 'Checklists', 'Reminder cards', 'Aftercare guides'],
    array[
      'New enquiry response sheet',
      'Vehicle intake form and condition photo checklist',
      'Service estimate, booking confirmation and appointment reminder templates',
      'Detail-day preparation and aftercare guides',
      'Review, referral, rebooking and damage-report templates'
    ],
    'detail-authority-client-experience-operations-kit.png',
    ''
  ),
  (
    'tpl-canva-detail-brand-foundation',
    'detail-authority-brand-foundation-kit',
    'The Detail Authority — Brand Foundation Kit',
    'cat-auto',
    'col-launch',
    799,
    1499,
    10,
    'A 10-page editable Canva brand foundation kit for auto detailers building a premium, consistent visual and messaging system.',
    'Use this kit to define the look, voice and content rules for a detailing brand before creating daily posts or sales assets. Replace the placeholders with your own logo, vehicle photography, palette, typography and message examples.',
    '/assets/canva-products/detail-authority-brand-foundation-kit.png',
    '#d28a38',
    '#151412',
    'Brand Kit',
    'Draft',
    array['Brand guide', 'Visual rules', 'Messaging guide'],
    array[
      'Brand board, logo placeholder sheet and colour palette sheet',
      'Typography and photography direction guides',
      'Social-media layout rules and brand voice guide',
      'Client-facing message examples',
      'Do/don’t visual guide and content calendar overview'
    ],
    'detail-authority-brand-foundation-kit.png',
    ''
  ),
  (
    'tpl-canva-premium-business-carousel',
    'premium-business-carousel-template',
    'Premium Business Carousel Template',
    'cat-coaching',
    'col-launch',
    299,
    699,
    5,
    'A 5-page editable business carousel for introducing a brand, explaining value, showing proof and guiding viewers toward a call to action.',
    'Built for service providers, consultants and small businesses, this carousel helps turn a vague offer into a clear story: what problem you solve, what you offer, what proof you have and what action people should take next.',
    '/assets/canva-products/premium-business-carousel-template.png',
    '#f0642f',
    '#191917',
    '5 Pages',
    'Draft',
    array['Carousel', 'Business introduction', 'Offer explainer'],
    array[
      '5 editable carousel pages',
      'Problem framing page',
      'Solution/services page',
      'Client proof page',
      'Call-to-action page with replaceable business, offer and contact details'
    ],
    'premium-business-carousel-template.png',
    ''
  )
on conflict (slug) do update set
  title = excluded.title,
  category_id = excluded.category_id,
  collection_id = excluded.collection_id,
  price = excluded.price,
  mrp = excluded.mrp,
  layout_count = excluded.layout_count,
  description = excluded.description,
  long_description = excluded.long_description,
  cover_url = excluded.cover_url,
  accent = excluded.accent,
  dark = excluded.dark,
  badge = excluded.badge,
  status = excluded.status,
  formats = excluded.formats,
  includes = excluded.includes,
  cover_name = excluded.cover_name;
